### ISSUE TITLE
Game can be started mutiple times

### ISSUE THREAD

**Issue by TitusKirch** [jggoebel/bashbrawl#3]
I already have a small bugfix that solves the problem without changing much. I will submit as PR

How to reproduce it:
![chrome_xePmoqol4B](https://github.com/user-attachments/assets/adccc4eb-3759-4efe-b35e-0fa2f8287e44)

Result:
![image](https://github.com/user-attachments/assets/213d9b21-a574-43c9-a14b-311ce3367a9a)

**Comment by jggoebel** [comment]
Yes i also stumbled across this issue but did not have time to look into this further - thank you for fixing this!!

**Comment by jggoebel** [comment]
What i also just realized is that we could disable user input during the 3 second wait time completely.

**Comment by TitusKirch** [comment]
> What i also just realized is that we could disable user input during the 3 second wait time completely.

I think this might even be the better solution.
